version: '3.8'

services:
  blog:
    image: blog-www
    env_file:
      - .env
    build: .
    # TODO:
    # Add health checks to monitor if the site is up
    restart: always
    volumes:
      - ./src:/blog
    ports:
      - "${OUTSIDE_PORT}:${BLOG_PORT}"
