name: Deploy

on:
  push:

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Wait For Check
      uses: fountainhead/action-wait-for-check@v1.0.0
      id: wait-for-test
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        checkName: test
        ref: ${{ github.event.pull_request.head.sha || github.sha }}
    - name: Deploy to production
      if: steps.wait-for-test.outputs.conclusion == 'success'
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.KEY }}
        port: ${{ secrets.PORT }}
        script: | 
          cd projects/blog
          git pull
          docker-compose up --build -d     
