name: build

on:
  push:
    branches: [main]

jobs:
  test:
    runs-on: ${{ matrix.os }} # runs a test on Ubuntu, Windows and macOS

    strategy:
      matrix:
        deno: ["v1.x", "nightly"]
        os: [macOS-latest, windows-latest, ubuntu-latest]

    steps:
      - name: Setup repo
        uses: actions/checkout@v2

      - name: Setup Deno
        uses: denolib/setup-deno@c7d7968ad4a59c159a777f79adddad6872ee8d96
        env:
          ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'
        with:
          deno-version: ${{ matrix.deno }}

      - name: Cache Dependencies
        run: deno cache --unstable deps.ts

      - name: Run Tests
        run: deno test -A --unstable tests/       
   
